name: Install MatBox

on:
  workflow_dispatch:
    inputs:
      matlab_release:
        required: false
        type: string
        default: 'latest'

jobs:
  install:
    name: Install MATLAB
    runs-on: ubuntu-latest

    steps:  
      - name: Set up MATLAB (${{ inputs.matlab_release }})
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ inputs.matlab_release }}

      - name: Install MatBox
        uses: ehennestad/matbox/.github/actions/install-matbox@a7782b9a8b1827ea69777f3ddbc23bf47a31c889
        with:
          mode: 'release'

      - name: Confirm on path MatBox
        uses: matlab-actions/run-command@v2
        with:
          command: |
            which('matbox.installRequirements')