name: Install MatBox

on:
  workflow_dispatch:
    inputs:
      matlab_release:
        required: false
        type: string
        default: 'latest'

      install_mode:
        description: 'Installation mode for MatBox (release or commit)'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - commit

jobs:
  install:
    name: Install MATLAB
    runs-on: ubuntu-latest

    steps: 
      - name: Show current
        run: pwd
      - name: List current
        run: ls
      - name: List work
        run: ls /home/runner/work/_actions

      - name: Set up MATLAB (${{ inputs.matlab_release }})
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ inputs.matlab_release }}

      - name: Install MatBox
        uses: ehennestad/matbox/.github/actions/install-matbox@bd8473480ff784699a26c108562eb2cf947dcbf8
        with:
          mode: ${{ inputs.install_mode }}

      - name: Confirm on path MatBox
        uses: matlab-actions/run-command@v2
        with:
          command: |
            which('matbox.installRequirements')


