name: Run Test Suite (test composite test action)

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'docs/reports/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
      - 'docs/reports/**'
      
  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests_comp:
    name: Run tests (MATLAB latest release)
    runs-on: ubuntu-latest
    steps:      
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest
          cache: true

      - name: Install MatBox
        uses: ehennestad/matbox/.github/actions/install-matbox@v0.9

      - name: Run tests
        uses: ehennestad/matbox/.github/actions/test-code@make-release-workflow-reusable
        with:
          code_directory: ${{ inputs.code_directory }}
          tools_directory: ${{ inputs.tools_directory }}

      - name: Restore MATLAB Path
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: |
            restoredefaultpath()
            savepath()
