name: Run tests

on:
  # Triggers the workflow on push to any branch other than main or PR to main
  # This way tests will run on any push to a feature branch and when feature 
  # branches are merged to main, but not repeated when PRs are actually merged. 
  push:
    branches-ignore: ["pipeline", "gh-badges"]
    paths-ignore:
      - '*README.md'
      - '*md'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

env:
  TOOLBOX_NAME: "My Sandbox"

jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test ${{ env.TOOLBOX_NAME }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out repo
        uses: actions/checkout@v4

      # Print all environment variables
      - name: Print Environment Variables
        run: env
