name: Call reusable test workflow

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'docs/reports/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
      
  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

jobs:
  cancel-non-latest:
    steps:
      - name: Cancel non-latest runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

  call-workflow-test-toolbox:
    uses: ehennestad/matbox/.github/workflows/reusable_test_workflow.yml@add-reusable-test-workflow
    secrets:
      commit_email_address: ${{ secrets.COMMIT_EMAIL_ADDRESS }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
