name: Run range test ${{ github.event.repository.name }}

on:
  push:
    branches-ignore: ["pipeline", "gh-badges"]
    paths-ignore:
      - '*README.md'
      - '*md'
      - '.github/**'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*README.md'
      - '*md'
      - '.github/**'

  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

env:
  TOOLBOX_NAME: "My Sandbox"

jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test ${{ github.event.repository.name }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out repo
        uses: actions/checkout@v4

      # Print all environment variables
      - name: Print Environment Variables
        run: env
